### ISSUE TITLE
Actually create assets

### ISSUE THREAD

**Issue by davidmehren** [foss-ag/design_id#3]
Currently, the Makefile is just a placeholder. It should actually create meaningful things.

**Comment by dragetd** [comment]
At least it creates one image right now. :)

What was the plan? Have all different kind of resolutions and colors auto-generated?

**Comment by Scosh** [comment]
I'm closing this issue, since it's become a bit too ambiguous and general as this project (and its issue page) have grown. Please look for more "concrete" issues to work on, or open them.

Also, like @dragetd said, the `Makefile` does actually make things now — even if it is still pretty minimal.

> What was the plan? Have all different kind of resolutions and colors auto-generated?

To answer this: yes, exactly. That is the plan — using the `base.ink.svg` file for now. In future, perhaps numerous files will auto-generate exports — but for now, we're only working on, and with, this one.
